### ISSUE TITLE
Feature: User can view and click through an FAQ accordion. 

### ISSUE THREAD

**Issue by NoahLett** [NoahLett/book-worm#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view and click through an FAQ accordion that addresses common questions new users will often have regarding the functionality and purpose of BookWorm. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The component will be a collapsible accordion that shows one answer to a specified question at a time. If the user already has an answer open and chooses to click on another question to view it's answer, the previous answer will "collapse". 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/110089434/210025747-883d58fd-2475-4598-8400-2c9b1bb1068b.png)
![image](https://user-images.githubusercontent.com/110089434/210025757-fb33b73b-156b-4c6f-8171-99cd886bee5a.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ⚡ Client Tasks
- [x] Create a faq.jsx file within the pages folder of the client directory. 
- [x] In the faq.jsx file, import React 
- [x] Create a React class component to with a props object containing title and text properties with their corresponding values. 
- [x] Declare this.state with a property of viewIndex and value of null. 
- [x] Define a method setOptionTopic with an a single parameter of index that will check if this.state.viewIndex is strictly equal to the value of index.
- [x] Bind this to the setOpenTopic method so the function works properly.
- [x] Define a render method that conditionally returns an open or closed "topic" in the accordion, dependent on the value of this.state.viewIndex.
- [x] Export the accordion.
- [x] Create the necessary CSS styling to match the above wireframes.
- [x] Verify that views are appealing in both mobile and desktop settings.

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
