### ISSUE TITLE
Feature: User can create an account with a unique username.

### ISSUE THREAD

**Issue by NoahLett** [NoahLett/book-worm#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can create an account with a unique username that will grant them privileges only logged in users have on the app. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The Sign Up page will include a form with required inputs that ask the user for their first and last names, a unique username, the city and state they reside in, and a password with confirmation of spelling. Upon submit, their user information will be stored in the users database, where they will be assigned a userId and their password will be stored in a hashed format. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/110089434/209858522-5345aa66-a91c-4ee8-a6ab-dd1e2a9f4265.png)
![image](https://user-images.githubusercontent.com/110089434/209858553-22ed5b68-1597-4cf8-b8e3-0360e8a4d539.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Ensure `schema.sql` contains a Users table with the correct column categories 

### ☁️ Server Tasks

- [x] On the server side, in index.js, create the necessary app.post function to allow for the submission of data to the database
- [x] Use argon2 to hash the user's password
- [x] Test the new function with HTTPie to ensure data is being sent properly and stored as intended 
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a new page called sign-up.jsx
- [x] Within sign-up.jsx, create a new class component called Registration 
- [x] Define a constructor function within sign-up.jsx
- [x] Establish this.state to include an object that contains the firstName, lastName, city, state, username and password properties, all with values of empty strings. 
- [x] Create a render method that returns a form with the necessary inputs to match the wireframes above.
- [x] Add the necessary attributes to each inputs (ie: required, autoFocus, id, name, classes, etc)
- [x] Create a handleChange method that will allow the user to see their typed responses within the inputs in live time. 
- [x] Create a handleSubmit method that will prevent default functionality of the browser upon submit and make a fetch POST request that submits the user's inputs

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
